[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true

[program:code-server]
command=code-server --bind-addr 0.0.0.0:8080 --auth none
autostart=true
autorestart=true

[program:jupyter]
command=jupyter notebook --ip=0.0.0.0 --port=8088 --allow-root --no-browser
autostart=true
autorestart=true
