[program:caddy]
command=/opt/homebrew/bin/caddy run --config %(ENV_REPO_ROOT)s/caddy/Caddyfile
directory=%(ENV_REPO_ROOT)s
autostart=true
autorestart=true
stdout_logfile=%(ENV_REPO_ROOT)s/logs/caddy.log
stderr_logfile=%(ENV_REPO_ROOT)s/logs/caddy.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
