[program:openkitty-panel]
command=/opt/homebrew/bin/node build/index.js
directory=/Users/travis/Developer/repos/neuralj/openkitty/panel
environment=PORT="3095",HOST="127.0.0.1",NODE_ENV="production"
autostart=true
autorestart=true
stdout_logfile=%(ENV_REPO_ROOT)s/logs/openkitty-panel.log
stderr_logfile=%(ENV_REPO_ROOT)s/logs/openkitty-panel.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
