[program:opensheeta-frontend]
command=/opt/homebrew/bin/node server.js
directory=/Users/travis/Developer/repos/neuralj/opensheeta/frontend
environment=PORT="3100",NODE_ENV="production"
autostart=true
autorestart=true
stdout_logfile=/Users/travis/Developer/repos/neuralj/opensheeta/logs/frontend.log
stderr_logfile=/Users/travis/Developer/repos/neuralj/opensheeta/logs/frontend.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
